import {
  colors,
  lightColors,
  darkColors,
  fontSizes,
  fontWeights,
  fonts,
  lineHeights,
  radii,
  space,
} from '@setgoh-ui/tokens'
import { createTheme, createThemeContract } from '@vanilla-extract/css'

const commonVars = {
  fontSizes,
  fontWeights,
  fonts,
  lineHeights,
  radii,
  space,
}

export const vars = createThemeContract({
  colors: {
    primaryA: null,
    primaryB: null,
    accent: null,
    negative: null,
    warning: null,
    positive: null,
    primaryATransparence8: null,
    primaryBTransparence20: null,
    backgroundPrimary: null,
    backgroundSecondary: null,
    backgroundTertiary: null,
    backgroundInversePrimary: null,
    backgroundInverseSecondary: null,
    contentPrimary: null,
    contentSecondary: null,
    contentTertiary: null,
    contentInversePrimary: null,
    contentInverseSecondary: null,
    contentInverseTertiary: null,
    borderOpaque: null,
    borderTransparent: null,
    borderSelected: null,
    borderInverseOpaque: null,
    borderInverseTransparent: null,
    borderInverseSelected: null,
    backgroundStateDisabled: null,
    backgroundOverlayArt: null,
    backgroundOverlayDark: null,
    backgroundOverlayLight: null,
    backgroundAccent: null,
    backgroundNegative: null,
    backgroundWarning: null,
    backgroundPositive: null,
    backgroundLightAccent: null,
    backgroundLightNegative: null,
    backgroundLightWarning: null,
    backgroundLightPositive: null,
    backgroundAlwaysDark: null,
    backgroundAlwaysLight: null,
    contentStateDisabled: null,
    contentOnColor: null,
    contentOnColorInverse: null,
    contentAccent: null,
    contentNegative: null,
    contentWarning: null,
    contentPositive: null,
    borderStateDisabled: null,
    borderAccent: null,
    borderAccentLight: null,
    borderNegative: null,
    borderWarning: null,
    borderPositive: null,
    white: null,
    black: null,
    whiteTransparence20: null,
    whiteTransparence30: null,
    blackTransparence0: null,
    blackTransparence8: null,
    blackTransparence16: null,
    blackTransparence20: null,
    blackTransparence30: null,
    magenta700: null,
    magenta600: null,
    magenta500: null,
    magenta400: null,
    magenta300: null,
    magenta200: null,
    magenta100: null,
    magenta50: null,
    purple700: null,
    purple600: null,
    purple500: null,
    purple400: null,
    purple300: null,
    purple200: null,
    purple100: null,
    purple50: null,
    cobalt700: null,
    cobalt600: null,
    cobalt500: null,
    cobalt400: null,
    cobalt300: null,
    cobalt200: null,
    cobalt100: null,
    cobalt50: null,
    blue700: null,
    blue600: null,
    blue500: null,
    blue400: null,
    blue300: null,
    blue200: null,
    blue100: null,
    blue50: null,
    teal700: null,
    teal600: null,
    teal500: null,
    teal400: null,
    teal300: null,
    teal200: null,
    teal100: null,
    teal50: null,
    green700: null,
    green600: null,
    green500: null,
    green400: null,
    green300: null,
    green200: null,
    green100: null,
    green50: null,
    lime700: null,
    lime600: null,
    lime500: null,
    lime400: null,
    lime300: null,
    lime200: null,
    lime100: null,
    lime50: null,
    yellow700: null,
    yellow600: null,
    yellow500: null,
    yellow400: null,
    yellow300: null,
    yellow200: null,
    yellow100: null,
    yellow50: null,
    orange700: null,
    orange600: null,
    orange500: null,
    orange400: null,
    orange300: null,
    orange200: null,
    orange100: null,
    orange50: null,
    red700: null,
    red600: null,
    red500: null,
    red400: null,
    red300: null,
    red200: null,
    red100: null,
    red50: null,
    brown700: null,
    brown600: null,
    brown500: null,
    brown400: null,
    brown300: null,
    brown200: null,
    brown100: null,
    brown50: null,
    gray900: null,
    gray800: null,
    gray700: null,
    gray600: null,
    gray500: null,
    gray400: null,
    gray300: null,
    gray200: null,
    gray100: null,
    gray50: null,
    platinum800: null,
    platinum700: null,
    platinum600: null,
    platinum500: null,
    platinum400: null,
    platinum300: null,
    platinum200: null,
    platinum100: null,
    platinum50: null,
    ignite300: null,
    ignite500: null,
    ignite700: null,
    ignite900: null,
  },
  fontSizes: {
    xxs: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    '4xl': null,
    '5xl': null,
    '6xl': null,
    '7xl': null,
    '8xl': null,
    '9xl': null,
  },
  fontWeights: {
    regular: null,
    medium: null,
    bold: null,
  },
  fonts: {
    default: null,
    code: null,
  },
  lineHeights: {
    shorter: null,
    short: null,
    base: null,
    tall: null,
  },
  radii: {
    px: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    full: null,
  },
  space: {
    0: null,
    1: null,
    2: null,
    3: null,
    4: null,
    5: null,
    6: null,
    7: null,
    8: null,
    10: null,
    12: null,
    16: null,
    20: null,
    40: null,
    64: null,
    80: null,
  },
})

export const lightThemeClass = createTheme(vars, {
  colors: {
    ...colors,
    ...lightColors,
  },
  ...commonVars,
})

export const darkThemeClass = createTheme(vars, {
  colors: {
    ...colors,
    ...darkColors,
  },
  ...commonVars,
})
